language: node_js
node_js:
  - "10"
services:
  - postgresql
  - docker

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=$DOCKER_USERNAME/expl-bot
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG .
  - docker push $REPO

notifications:
  webhooks:
  # Telegram notification
  - https://fathomless-fjord-24024.herokuapp.com/notify
