apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expl-bot.fullname" . }}-telegram-token
  labels:
    {{- include "expl-bot.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.telegram.token | b64enc | quote }}