name: CI

on:
  push:
    branches:
      - master
      - development

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: expl-bot

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest
    container: node:12
    defaults:
      run:
        shell: bash

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm ci

      - run: npm run test
        env:
          PG_CONNECTION_STRING: postgres://postgres:postgres@postgres:5432/postgres

      - name: Generate Telegram message
        if: ${{ always() }}
        id: telegram_message
        run: |
          if [ $STATUS == "success" ]
          then
            MESSAGE=✅
          else
            MESSAGE=❌
          fi

          MESSAGE="$MESSAGE \"${{ github.event.head_commit.message }}\""
          MESSAGE="$MESSAGE ([#$( echo "${{ github.sha }}" | head -c 7)](https://github.com/${{ github.repository	 }}/commit/${{ github.sha }}))"
          MESSAGE="$MESSAGE @ \`${GITHUB_REF#refs/heads/}\`"
          MESSAGE="$MESSAGE by *${{ github.actor }}*"

          echo "::set-output name=message::$MESSAGE"
        env:
          STATUS: ${{ job.status }}

      - name: Send notification
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.telegram_message.outputs.message }}
          format: markdown
        env:
          PLUGIN_WEBPAGE_PREVIEW: false

  # Push image to GitHub Packages.
  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
